In [9]:
#Importamos las librerías que vamos a utilizar
#Banco Mundial con wbdata (PBI per cápita, gasto en educación, población)

import wbdata
import pandas as pd
import datetime

| Indicador                  | Código              |
| -------------------------- | ------------------- |
| PBI per cápita             | `NY.GDP.PCAP.CD`    |
| Gasto en educación (% PBI) | `SE.XPD.TOTL.GD.ZS` |
| Población total            | `SP.POP.TOTL`       |

In [10]:
#Crear diccionario de indicadores

indicadores = {
    'NY.GDP.PCAP.CD': 'pbi_per_capita',
    'SE.XPD.TOTL.GD.ZS': 'gasto_educacion',
    'SP.POP.TOTL': 'poblacion'
}

In [11]:
#Definir rango de años

fecha_inicio = datetime.datetime(2020, 1, 1)
fecha_fin = datetime.datetime(2024, 1, 1)

In [12]:
#Descargar datos

df_wb = wbdata.get_dataframe(
    indicadores,
    date=(fecha_inicio, fecha_fin)
)

In [13]:
#Convertir índices en columnas

df_wb = df_wb.reset_index()

In [14]:
#Ver resultado

df_wb.head()

,country,date,pbi_per_capita,gasto_educacion,poblacion
0,Africa Eastern and Southern,2024,1615.396356,NaN,769280888.0
1,Africa Eastern and Southern,2023,1571.449189,3.962293,750491370.0
2,Africa Eastern and Southern,2022,1679.327622,3.697668,731821393.0
3,Africa Eastern and Southern,2021,1562.416175,4.368379,713090928.0
4,Africa Eastern and Southern,2020,1351.591669,4.090565,694446100.0

In [15]:

df_wb.describe()

       pbi_per_capita  gasto_educacion     poblacion
count     1264.000000       829.000000  1.325000e+03
mean     18872.581881         4.263443  3.252141e+08
std      28655.476775         1.995183  1.002491e+09
min        219.424831         0.000006  9.646000e+03
25%       2482.699133         3.138370  1.790151e+06
50%       7218.778220         3.984180  1.067212e+07
75%      23806.930814         5.120250  6.661761e+07
max     288001.433369        16.390530  8.141809e+09